# -*- coding: utf-8 -*-
"""capacitaPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaC7NQg_WZBb_c22WdRDG-SgdSJqWPM0

# Exercircio 1
"""

# comentario
nome = input("digite o nome: ")
sobrenome = input("digite o sobrenome: ")
a = int(input("digite o primero número inteiro:\n"))
b = int(input("digite o segundo número inteiro:\n"))
print(a , "+", b, "=", a+b)
print("seu nome é:", nome , sobrenome)

ano = int(input("Defina o ano atual: "))
nascimento = int(input("Digite o ano de seu nascimento: "))
print("Vocé tem", ano-nascimento ,"anos!")

peso = float(input("Digite o seu peso: "))
altura = float(input("Digite a sua altura: "))
imc = peso/(altura*altura)
print("Seu IMC é:", imc)

"""# Exercicio 2


"""

palavra = "muito legal"
print("kk"*3 + palavra, "foda" + palavra[4] + palavra[5:11] , type(palavra))
print(f"A palavra é {palavra} esse codigo")

idade = 18
print(idade > 18)
print(int(idade > 18))

